### ISSUE TITLE
2.0 leftovers

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-component-explorer#116]
List of loopback-explorer improvements to possibly implement on top of https://github.com/strongloop/loopback-explorer/pull/115:
- [x] sort routes - model routes first, relation routes next
- [ ] Support built-in models:
  - [x] MongoDB's ObjectID
  - [x] GeoPoint
  - [ ] ReadableStream (as a File?) - needs a spike
- [ ] Add a config option to specify global security definition
  object https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-definitions-object
- [ ] For routes with multiple return values, generate a new schema instead
  of reusing generic "object"
- https://github.com/strongloop-internal/scrum-loopback/issues/667 support `.model` for both accepts & returns
- [ ] #105 support strong-remoting's option for a custom response code
- [ ] define new LDL syntax for specifying errors via status-code-indexed object
- [ ] https://github.com/strongloop-internal/scrum-loopback/issues/668 Fix model definition to set `schema.title` and prevent "Inline model" text in GUI ([source](https://github.com/swagger-api/swagger-js/blob/571264e6ca6fc20569dcc0fdab0987261b079bd0/lib/schema-markup.js#L221))
- [ ] Support OAuth2 scopes - see https://github.com/strongloop/loopback-explorer/pull/115#discussion_r38143665
- [ ] https://github.com/strongloop-internal/scrum-loopback/issues/669 Consider supporting per-method "produces" and "consumes" configuration - see https://github.com/strongloop/loopback-explorer/pull/115#discussion_r38143589

**Comment by bajtos** [comment]
@0candy This is sort of a placeholder/linkpost story to keep track of all leftovers from my work on explorer@2.0. I am assigning it to you as you are the new repo expert. Some of the subtasks have already standalone stories, I think we should eventually get stories created for all subtasks.

For the purpose of Sprint 86 planning, could you please take few of those subtasks that are clear enough from the brief description available here, create new GH issues for them, put these new GH issues to `#plan` column and provide estimates, so that we can use them on Tuesday for sprint planning?

I think these may be good candidates:
 - support .model for both accepts & returns
 - Fix model definition to set schema.title and prevent "Inline model" text in GUI
 - Consider supporting per-method "produces" and "consumes" configuration
