### ISSUE TITLE
Rename to follow component naming convention

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-component-explorer#123]
Should this module be renamed to loopback-component-explorer to match the naming convention used by the other LB components:
- loopback-component-push
- loopback-component-storage
- loopback-component-passport
- loopback-component-oauth2

Is there a counter-argument for doing so?

**Tasks**
 - [x] #125 rename the module 
 - [x]  strongloop-internal/ci-infrastructure#15 update Jenkins configuration (@bajtos) 
 - [x] update example app (@crandmck) see https://github.com/strongloop/loopback-example-app/pull/79
 - [x] Update generator-loopback to use this new module - covered by  https://github.com/strongloop/generator-loopback/issues/113 
 - [ ] _In Progress_ update other example apps to use the new component - see https://github.com/strongloop-internal/scrum-loopback/issues/495 (@crandmck)
 - [ ] update other projects like loopback-workspace to use the new component (who?)
 - [x] update the documentation (@crandmck)
 - [x] post a message to the mailing list to let people know about the new module name (@crandmck)
 - [ ] eventually add a deprecation warning to loopback-explorer@2.0.1 so that npm install nudges people toward upgrading to loopback-component-explorer (@bajtos)

**Comment by bajtos** [comment]
> Should this module (loopback-explorer) be renamed to loopback-component-explorer to match the naming convention used by the other LB components:
- loopback-component-push
- loopback-component-storage
- loopback-component-passport
- loopback-component-oauth2

> Is there a counter-argument for doing so?

I'm fine with both loopback-explorer and loopback-component-explorer.

@raymondfeng @ritch @superkhau @altsang @ijroth Thoughts?

**Comment by altsang** [comment]
:+1: I think that makes a lot of sense

**Comment by superkhau** [comment]
Those renames make sense to me.

+1

**Comment by raymondfeng** [comment]
I'm fine with `loopback-component-explorer` or `loopback-explorer`.

**Comment by ritch** [comment]
I want `loopback-component-*` to have some significance for information architecture purposes. If you can load it using `boot()`s component loader, it should have that designation. I'm fairly certain this is true for explorer, so +1 from me.

**Comment by crandmck** [comment]
I renamed the module in GitHub, and above PR is for other related changes.

**Comment by crandmck** [comment]
Re
> post a message to the mailing list to let people know about the new module name

I will do this, but I would like to summarize what it takes for a module to be a component so I can explain clearly why we renamed it.  

I asked this on Slack, but got no response.
@bajtos @raymondfeng @ritch 

Also, should we create issues to track the work required to make the other "wannabe" components into ​_actual_​ components?

**Comment by bajtos** [comment]
> what it takes for a module to be a component so I can explain clearly why we renamed it

The bare minimum is to export a `function(app, options)` as the main module export, that's the API contract. I don't think there are any other requirements/constraints.

**Comment by bajtos** [comment]
Compare that with express middleware, which exports `function(options)` that is supposed to return a `function(req, res, next)` or `function(err, req, res, next)`.

**Comment by crandmck** [comment]
OK, posted https://groups.google.com/forum/#!topic/strongloop/dB7hyw6ErdU.

**Comment by crandmck** [comment]
Currently working on https://github.com/strongloop-internal/scrum-loopback/issues/495

**Comment by crandmck** [comment]
@bajtos I'm currently working on https://github.com/strongloop-internal/scrum-loopback/issues/495 so the only remaining items in the task list are:
 - [ ] update other projects like loopback-workspace to use the new component (who?)
 - [ ] eventually add a deprecation warning to loopback-explorer@2.0.1 so that npm install nudges people toward upgrading to loopback-component-explorer (@bajtos)

Do you want to take one or both of these?  If so, please assign this issue to yourself.

**Comment by bajtos** [comment]
> Do you want to take one or both of these? If so, please assign this issue to yourself.

Sounds like a plan :smile:

**Comment by bajtos** [comment]
> update other projects like loopback-workspace to use the new component

Workspace has been already updated, see https://github.com/strongloop/loopback-workspace/pull/230

> eventually add a deprecation warning to loopback-explorer@2.0.1 so that npm install nudges people toward upgrading to loopback-component-explorer

Done.
